name: Build for ARM64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Download dependencies
      run: |
        go mod tidy

    - name: Build for ARM64
      run: |
        GOOS=linux GOARCH=arm64 go build -o oledmonitor ./cmd/oledmonitor

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: oledmonitor-arm64
        path: oledmonitor
