name: Build for Raspberry Pi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'  # Adjust to your Go version

    - name: Install dependencies
      run: go mod tidy
      
    - name: Build for Raspberry Pi 4 (arm64)
      run: GOOS=linux GOARCH=arm64 go build -v -o oledmonitor-arm64 ./cmd/oledmonitor
      
    - name: Build for Raspberry Pi 3/Zero/etc (armv7)
      run: GOOS=linux GOARCH=arm GOARM=7 go build -v -o oledmonitor-armv7 ./cmd/oledmonitor
    
    - name: Upload ARM64 binary
      uses: actions/upload-artifact@v3
      with:
        name: oledmonitor-arm64
        path: oledmonitor-arm64
        
    - name: Upload ARMv7 binary
      uses: actions/upload-artifact@v3
      with:
        name: oledmonitor-armv7
        path: oledmonitor-armv7
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          oledmonitor-arm64
          oledmonitor-armv7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
